# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PickStats(betterproto.Message):
    mu_r: float = betterproto.double_field(1)
    mu_g: float = betterproto.double_field(2)
    mu_b: float = betterproto.double_field(3)
    perc_r: float = betterproto.double_field(4)
    perc_g: float = betterproto.double_field(5)
    prec_b: float = betterproto.double_field(6)
    sigma_r: float = betterproto.double_field(7)
    sigma_g: float = betterproto.double_field(8)
    sigma_b: float = betterproto.double_field(9)


@dataclass
class ClipboardContent(betterproto.Message):
    rows: List["PickStats"] = betterproto.message_field(1)


@dataclass
class PickedCircle(betterproto.Message):
    center_x: float = betterproto.double_field(1)
    center_y: float = betterproto.double_field(2)
    radius: float = betterproto.double_field(3)
    img_file_name: str = betterproto.string_field(4)
